### PR TITLE
Snowplains tileset fixes

### PR DESCRIPTION
**Pull request by dorkster**
- Set y-offset for snowplains_ice tiles to 32px in tmx test map
- Fix alignment of snowplains_other tiles in tileset_snowplains.png
- Fixed the wooden towers in snowplains_other being clipped improperly

### CODE REVIEW

**Comment by igorko** [comment]
Look in Flare
image

Look in Tiled
image

Can we do something with this? I mean black tiles on right side of screenshot and black tile on left side of bridge

Map file https://www.dropbox.com/s/nx5card15e8bf7p/town.tmx?dl=0

**Comment by igorko** [comment]
Those gaps near bridge can be caused by using wrong tiles, but anyway this can be an issue...

**Comment by igorko** [comment]
@dorkster Looks like I have fixed above issue with https://github.com/igorko/flare-mod-noname/commit/3657ac89ff8b0fc35c7442111fbd6444a8d23938

Just changed offsets for 32x32 background tiles (snowplains_other) from -16 to 16. Does it look correct for you?
How about that stuff with clearing above tile when using background tiles? I do not see this happen for grassland...

**Comment by dorkster** [comment]
Yes, changing from -16 to 16 fixes the issue.

When you say that the above tile is cleared when using background tiles, are you talking about the water/ice tiles that are below the ground level? Because if so, that is correct behavior that happens with the water tiles in the grassland tileset.

**Comment by igorko** [comment]
Hm, not sure. I only can tell that issue happens with ice/snow tiles from snowplains_ice section. These tiles are 64 px in height. I will doublecheck it.

**Pull request merged**
